name: Build Android APK

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'assets/**'
      - 'ios/**'
      - '__tests__/**'
      - '*.md'
      - '.gitignore'
      - 'jest.*'
      - '.eslintrc.*'
      - '.prettier*'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: cd android && ./gradlew assembleRelease --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Secret-App-Release-APK
          path: android/app/build/outputs/apk/release/app-release.apk
